### ISSUE TITLE
[Cortex M3 - Refactoring] To add the last commits to the CortexM3 branch

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/bootloader-stm32#23]
The last commits of the Cortex M3 have been lost. It is necessary to add them to the CortexM3 branch.
@francisjjp , you have them in your local branch. Please add them to the current CortexM3 branch

**Comment by francisjjp** [comment]
@ralcaide .Last commits have been added.

**Comment by ralcaide** [comment]
Thanks Francis. I've already created the needed tag in the repository.
